// <auto-generated />
using System;
using ActsValidator.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ActsValidator.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319070800_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActsValidator.Domain.AiRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("collation_id")
                        .HasColumnType("uuid")
                        .HasColumnName("collation_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_requests");

                    b.HasIndex("collation_id")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_requests_collation_id");

                    b.ToTable("ai_requests", (string)null);
                });

            modelBuilder.Entity("ActsValidator.Domain.Collation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Act1Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("act1name");

                    b.Property<string>("Act2Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("act2name");

                    b.Property<int>("CoincidencesCount")
                        .HasColumnType("integer")
                        .HasColumnName("coincidences_count");

                    b.Property<string>("CollationErrors")
                        .HasColumnType("jsonb")
                        .HasColumnName("collation_errors");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RowsProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("rows_processed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_collations");

                    b.ToTable("collations", (string)null);
                });

            modelBuilder.Entity("ActsValidator.Domain.AiRequest", b =>
                {
                    b.HasOne("ActsValidator.Domain.Collation", "Collation")
                        .WithOne()
                        .HasForeignKey("ActsValidator.Domain.AiRequest", "collation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_requests_collations_collation_id");

                    b.Navigation("Collation");
                });
#pragma warning restore 612, 618
        }
    }
}
