// <auto-generated />
using System;
using ActsValidator.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ActsValidator.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412191030_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActsValidator.Domain.Collation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Act1Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("act1name");

                    b.Property<string>("Act2Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("act2name");

                    b.Property<int>("CoincidencesCount")
                        .HasColumnType("integer")
                        .HasColumnName("coincidences_count");

                    b.Property<string>("CollationErrors")
                        .HasColumnType("jsonb")
                        .HasColumnName("collation_errors");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RowsProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("rows_processed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_collations");

                    b.ToTable("collations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
