// <auto-generated />
using System;
using ActsValidator.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ActsValidator.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214203918_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActsValidator.Domain.AiRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiDiscrepancies")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_discrepancies");

                    b.Property<Guid>("CollationId")
                        .HasColumnType("uuid")
                        .HasColumnName("collation_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_ai_requests");

                    b.HasIndex("CollationId")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_requests_collation_id");

                    b.ToTable("ai_requests", (string)null);
                });

            modelBuilder.Entity("ActsValidator.Domain.Collation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Discrepancies")
                        .HasColumnType("jsonb")
                        .HasColumnName("discrepancies");

                    b.HasKey("Id")
                        .HasName("pk_collations");

                    b.ToTable("collations", (string)null);
                });

            modelBuilder.Entity("ActsValidator.Domain.AiRequest", b =>
                {
                    b.HasOne("ActsValidator.Domain.Collation", null)
                        .WithOne("AiRequest")
                        .HasForeignKey("ActsValidator.Domain.AiRequest", "CollationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_requests_collations_collation_id");
                });

            modelBuilder.Entity("ActsValidator.Domain.Collation", b =>
                {
                    b.OwnsMany("ActsValidator.Domain.Shared.ValueObjects.CollationRow", "Act1", b1 =>
                        {
                            b1.Property<Guid>("CollationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<decimal>("Credit")
                                .HasColumnType("numeric");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("Debet")
                                .HasColumnType("numeric");

                            b1.Property<int>("SerialNumber")
                                .HasColumnType("integer");

                            b1.HasKey("CollationId", "__synthesizedOrdinal")
                                .HasName("pk_collations");

                            b1.ToTable("collations");

                            b1
                                .ToJson("act1")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CollationId")
                                .HasConstraintName("fk_collations_collations_collation_id");
                        });

                    b.OwnsMany("ActsValidator.Domain.Shared.ValueObjects.CollationRow", "Act2", b1 =>
                        {
                            b1.Property<Guid>("CollationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<decimal>("Credit")
                                .HasColumnType("numeric");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("Debet")
                                .HasColumnType("numeric");

                            b1.Property<int>("SerialNumber")
                                .HasColumnType("integer");

                            b1.HasKey("CollationId", "__synthesizedOrdinal");

                            b1.ToTable("collations");

                            b1
                                .ToJson("act2")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CollationId")
                                .HasConstraintName("fk_collations_collations_collation_id");
                        });

                    b.Navigation("Act1");

                    b.Navigation("Act2");
                });

            modelBuilder.Entity("ActsValidator.Domain.Collation", b =>
                {
                    b.Navigation("AiRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
